version: '2.1'

services:
  nodejs:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: portfolio-frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.capicua.org.es`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=8080"
    networks:
      - traefik-global-proxy
    mem_limit: 300m
    mem_reservation: 100m

networks:
  traefik-global-proxy:
    external: true
